### ISSUE TITLE
Not working at all 

### ISSUE THREAD

**Issue by llchristopherson** [jcadduono/interface_addons_claw#2]
As of today 7/15/23, Claw stopped working. It no longer does anything. Can you please look into this?

**Comment by jcadduono** [comment]
i dont recommend using it, i havent played feral since 10.0 and the apl has gone through major changes, even if i fix it it will still be kind of wrong

**Comment by jcadduono** [comment]
doned, mostly untested, but up to date with the code base of my other class addons for now

**Comment by llchristopherson** [comment]
THANK YOU!!!
________________________________
