### ISSUE TITLE
Maj 11.0

### ISSUE THREAD

**Issue by Crow01120** [jcadduono/interface_addons_claw#4]
Hello, can you update for wow retail 11.0.2.

Thx

**Comment by jcadduono** [comment]
updated the core but cba to update the apl right now so it still is in DF season 1 mode lol
you can DL builds from adduono.com/addons/claw
but I probably won't get around to updating the APL until I start playing feral again, so it will probably not work the best if anythings changed

**Comment by jcadduono** [comment]
ok I put a half-assed build up 11.0.2-2, kinda works for cats & bears using Druid of the Claw hero talents
only made it cause I decided to do delves on my druid for some reason, cause right now it's just my gathering toon
